### PR TITLE
Fix typing for commonly used callables

### PR DESCRIPTION
**Pull request by kalfa**
Fix typing for `raises()` `isinstance_of()` and `with_args()`, to satisfy to mypy and pyright linting

### CODE REVIEW

**Comment by brunns** [comment]
Looks like you are missing some imports.

**Comment by kalfa** [comment]
there you go, apologies.

I did the edit directly on github, and of course that was not a good choice ;-)

**Comment by kalfa** [comment]
ok, something else failed. 

It seems that those failures were the reasons raises was untyped?

Not sure I understand right now the problem, I will look into this later (but open to suggestions).

**Comment by kalfa** [comment]
This is my first patch to the project, since I wanted to have test not continuously failing type checking.

I understand that those tests failing for 3.12 on various platform are advisory. they seem to underline linting problems that were there before.

**Comment by brunns** [comment]
FWIW, I can't get the `lint` target running locally. On the first run it reformats the code, and on a second run it objects to the code it's just changed.

**Comment by kalfa** [comment]
yes, noticed that. I thought it was something I did with my local linters, and forced-pushed a basic change, but it was reapplied

**Comment by offbyone** [comment]
I'm gonna be traveling the next couple of days, but I'll look into it. 

I suppose we're coming up on the point where a minor release also makes sense. :D

**Pull request merged**
