### PR TITLE
The release workflow should only run for tagged releases

### PR DESCRIPTION
**Pull request by brunns**
Is this right? I wouldn't expect this workflow to run for all pushes to main, let alone for pull requests.

### CODE REVIEW

**Comment by offbyone** [comment]
I want this workflow to run against all of them, tbh. 

On push to `main` it publishes to the _test_ PyPi. That's only available to committers.

On PR, though, it runs the `hynek/build-and-inspect-python-package@v1` action, which does a bunch of PR-level packaging verification.

You can see a good example of a run here: https://github.com/hamcrest/PyHamcrest/actions/runs/6009538827/job/16299682463?pr=239

Unless you're seeing something I'm not, I'd like to leave this as it was.

**Comment by offbyone** [comment]
Oh... that's interesting. I guess I didn't consider that case, since I don't develop on `main` on my fork. 

I'd be interested in a change that limits the later steps to this workflow to only run on the primary repository; we could extend the match check down in the workflow to limit it to `hamcrest/PyHamcrest`?

**Comment by brunns** [comment]
Or I could just come to terms with working on branches like a good github citizen. :-)

**Comment by offbyone** [comment]
Both are valid options, but IMO you're not doing anything wrong by working on `main`, so I'm more than happy to see the workflow handle that case.

**Comment by brunns** [comment]
List looks like it might work for us: https://github.com/prisma/prisma/issues/3539#issuecomment-690260573

**Pull request closed without merging**
