### PR TITLE
Improve string representation of matcher in allure report

### PR DESCRIPTION
**Pull request by Denis-Alexeev**
Matchers in allure report now look like:
<hamcrest.core.core.isnot.IsNot object at 0x7f7262d17c40>

PR purpose:
Make it look more pretty

### CODE REVIEW

**Comment by offbyone** [comment]
I would prefer something closer to this:

```python
    def __repr__(self) -> str:
        """Returns the description."""
        return "<{}({})>".format(self.__class__.__name__, truncate(self.out, 60))
```

Basically, I don't think losing the type info is a good plan, _and_ having the debug repr be an unbounded string also has issues. You'd need to implement the `truncate` method if we don't have one somewhere else in the library.

Also, if you do this, please put a oneliner in `changelog.d` for it, probably as a "[feature](https://github.com/twisted/towncrier#news-fragments)".

**Comment by Denis-Alexeev** [comment]
I've fixed the code according to you remarks. Not sure about the reason for CI failure. Could you please help me with that?

**Comment by brunns** [comment]
Re the CI failure - if you run `tox -e lint` before your commit, I believe `black` has some formatting changes.

I think this needs a test of some kind, too.

**Comment by brunns** [comment]
Tests (In `BaseMatcherTest`) might look something like:

```python


    def testMatcherReprShouldDescribeMatcher(self):
        assert repr(FailingBaseMatcher()) == "FailingBaseMatcher(SOME DESCRIPTION)"

    def testMatcherReprShouldTruncateLongDescription(self):
        class LongDescriptionMatcher(BaseMatcher):
            def describe_to(self, description):
                description.append_text("1234 " * 13)
                
        assert repr(LongDescriptionMatcher()) == "LongDescriptionMatcher(1234 1234 1234 1234 1234 1234 1234 1234 1234 1234 1234 ...)"
```

**Comment by brunns** [comment]
The PR is just awaiting tests AFAIC.

**Comment by Denis-Alexeev** [comment]
Hello guys! Sorry for the delay. Could you please take a look and give your comments if needed?

**Comment by brunns** [comment]
Absolutely - I'll take a look on Monday, when I'm back at my computer.

**Pull request merged**
