### PR TITLE
Mark Python 3.12 as experimental for now.

### PR DESCRIPTION
**Pull request by brunns**

### CODE REVIEW

**Comment by offbyone** [comment]
Is this still needed now that the upstream is fixed?

**Comment by brunns** [comment]
Maybe not - but I am seeing breakage from Python 3.12 in other places - for example, due to https://github.com/python/cpython/issues/103329 - and it's possible we'll see more in future prereleases.

**Comment by offbyone** [comment]
I assume we'll want to know about that; is the idea that our CI would succeed but we'd notice a failing check? I'm not convinced :D 

Can you make that conditional on it being a PR? I'm fine with the weekly check build sending us a nastygram if it's failing.

**Comment by brunns** [comment]
Sure, you're right - probably not worth bothering with now we don't have an upstream failure.

**Pull request closed without merging**
