### PR TITLE
[WIP] 2018

### PR DESCRIPTION
**Pull request by moshez**

### CODE REVIEW

**Comment by offbyone** [comment]
Looks like the travis config needs to be incremented too. Otherwise, LGTM. Honestly, I'd be happy to dump anything below 3.4 and 2.7, assuming someone wants to write the changelog appropriately :)

**Comment by brunns** [comment]
Might be worth adding Python 3.7 to the mix now it's out?

**Comment by brunns** [comment]
There have been a number of updates to the build since thes PR was submitted - I think it's obsolete at this point. Shall I close it?

**Comment by brunns** [comment]
I think we are covering all current versions now.

**Pull request closed without merging**
