### PR TITLE
Do not convert description to str() and test for that

### PR DESCRIPTION
**Pull request by pupssman**
Improves on #48 by adding test

### CODE REVIEW

**Comment by sh0ked** [comment]
@pupssman when this PR is merged?

**Comment by pupssman** [comment]
@offbyone promised to include that in 2.0, but it is yet to be released. Looks like PR gonna be merged when the active work starts on 2.0.

**Comment by offbyone** [comment]
I’m going to back port this to the 1.8 branch and release 1.8.2 with it; I just have to get my tests running first.


—
Chris
offbyone on GitHub, offby1 on twitter

**Comment by offbyone** [comment]
Merged

**Pull request closed without merging**
