### PR TITLE
Don't recommend "import *" form.

### PR DESCRIPTION
**Pull request by brunns**

### CODE REVIEW

**Comment by offbyone** [comment]
Okay, I won't merge this super hastily; if you need to add more, just merge 'em when you're done :)

**Comment by brunns** [comment]
Yeah, sorry - I was being lazy, editing through the web. I'll do it properly...

(I need to look at the build, too.)

**Comment by offbyone** [comment]
Yeah, that's on my list too; bit rot... yay.

**Comment by brunns** [comment]
I've been considering running my CI builds on a schedule as well as on push, [like so](https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events), so I'd at least get an early heads up to stuff breaking due to something 3rd party.

**Comment by brunns** [comment]
Would you consider something like https://github.com/brunns/mbtest/blob/master/.github/workflows/ci.yml#L6?

**Comment by offbyone** [comment]
Yeah, definitely.

**Pull request merged**
